---
- name: Reach out to remote probes and troubleshoot routing
  hosts: all
  gather_facts: no
  vars:
    ansible_command_timeout: 120
    destIP: 1.1.1.1
    srcIP: 0.0.0.0

    method: slack

    email_host: smtp.gmail.com
    email_port: 587
    email_to: Greg Sowell <ILoveTacos@gregsowell.com>
    email_subject: Ansible-report
#    email_user: gmailuseraccount@gmail.com
#    email_pword: password-for-gmail-account

    slack_channel: '#ansible'
#    slack_token: thisis/thetoken/givenbyslackwebhook

  tasks:

    - name: Ping Destination
      routeros_command:
        commands:
          - "/ping count=10 {{ destIP }}"
      register: pings

    - name: Ping Source
      routeros_command:
        commands:
          - "/ping count=10 {{ srcIP }}"
      register: pings_source
      when: srcIP != "0.0.0.0"

    - name: Traceroute Destinations
      routeros_command:
        commands:
          - "/tool traceroute count=1 {{ destIP }}"
      register: traces

    - name: Traceroute source
      routeros_command:
        commands:
          - "/tool traceroute count=1 {{ srcIP }}"
      register: traces_source
      when: srcIP != "0.0.0.0"

    - name: display output for no source
      set_fact:
        send_msg: "##################Testing to {{ destIP }}##################\n##################{{ inventory_hostname }}##################\n===pings===\n{{ pings.stdout|join('\n') }}\n===traces===\n{{ traces.stdout|join('\n') }}\n\n"
      when: srcIP == "0.0.0.0"

    - name: display output with source
      set_fact:
        send_msg: "##################Testing to {{ destIP }}##################\n##################{{ inventory_hostname }}##################\n===pings destination===\n{{ pings.stdout|join('\n') }}\n===traces destination===\n{{ traces.stdout|join('\n') }}\n===pings source===\n{{ pings_source.stdout|join('\n') }}\n===traces source===\n{{ traces_source.stdout|join('\n') }}\n\n"
      when: srcIP != "0.0.0.0"

    - name: send message through slack
      when: method == 'slack'
      slack:
        token: "{{ slack_token }}"
        msg: "{{ send_msg }}"
        channel: "{{ slack_channel }}"
#        thread_id: 1539917263.000100
        parse: 'none'
      delegate_to: localhost

    - name: Sending an e-mail using Gmail SMTP servers
      when: method == 'email'
      mail:
        host: "{{ email_host }}"
        port: "{{ email_port }}"
        username: "{{ email_user }}"
        password: "{{ email_pword }}"
        to: "{{ email_to }}"
        subject: "{{ email_subject }}"
        body: "{{ send_msg }}"
      delegate_to: localhost
