---
- name: Change wlan2 radio power
  connection: network_cli
  gather_facts: false
  hosts: lab_mikrotiks
  tasks:

    - name: Change wlan2 radio power
      routeros_command:
        commands: /interface wireless set [ find default-name=wlan2 ] antenna-gain=15 frequency-mode=regulatory-domain installation=indoor distance=indoor
