---
- name: Enable wlan2 ANI
  connection: network_cli
  gather_facts: false
  hosts: lab_mikrotiks
  tasks:

    - name: Enable wlan2 ANI
      routeros_command:
        commands: /interface wireless set [ find default-name=wlan2 ] adaptive-noise-immunity=ap-and-client-mode
