---
# tasks file for mtk-dude-backup
  - name: Issue the backup database command
    routeros_command:
      commands:
        - "/dude export-db backup-file={{ bup_file }}"



  - name: Delete the backup file on the router
    routeros_command:
      commands:
        - "/file remove [/file find name={{ bup_file }}]"
